/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cbc_low_Create */

#ifndef _Included_cbc_low_Create
#define _Included_cbc_low_Create
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbc_low_Create
 * Method:    create_connect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_create_1connect
  (JNIEnv *, jobject);

/*
 * Class:     cbc_low_Create
 * Method:    create_disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1disconnect
  (JNIEnv *, jobject);

/*
 * Class:     cbc_low_Create
 * Method:    create_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1start
  (JNIEnv *, jobject);

/*
 * Class:     cbc_low_Create
 * Method:    create_passive
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1passive
  (JNIEnv *, jobject);

/*
 * Class:     cbc_low_Create
 * Method:    create_safe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1safe
  (JNIEnv *, jobject);

/*
 * Class:     cbc_low_Create
 * Method:    create_full
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1full
  (JNIEnv *, jobject);

/*
 * Class:     cbc_low_Create
 * Method:    create_spot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1spot
  (JNIEnv *, jobject);

/*
 * Class:     cbc_low_Create
 * Method:    create_cover
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1cover
  (JNIEnv *, jobject);

/*
 * Class:     cbc_low_Create
 * Method:    create_demo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1demo
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_cover_dock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1cover_1dock
  (JNIEnv *, jobject);

/*
 * Class:     cbc_low_Create
 * Method:    create_mode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_create_1mode
  (JNIEnv *, jobject);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_mode
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1mode
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_lbump
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1lbump
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_rbump
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1rbump
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_lwdrop
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1lwdrop
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_cwdrop
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1cwdrop
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_rwdrop
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1rwdrop
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_wall
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1wall
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_lcliff
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1lcliff
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_lfcliff
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1lfcliff
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_rfcliff
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1rfcliff
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_rcliff
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1rcliff
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_vwall
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1vwall
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_overcurrents
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1overcurrents
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_infrared
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1infrared
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_advance_button
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1advance_1button
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_play_button
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1play_1button
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_normalized_angle
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1normalized_1angle
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    set_create_normalized_angle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_set_1create_1normalized_1angle
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_total_angle
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1total_1angle
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    set_create_total_angle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_set_1create_1total_1angle
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_distance
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1distance
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    set_create_distance
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_set_1create_1distance
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_battery_charging_state
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1battery_1charging_1state
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_battery_voltage
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1battery_1voltage
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_battery_current
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1battery_1current
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_battery_temp
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1battery_1temp
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_battery_charge
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1battery_1charge
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_battery_capacity
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1battery_1capacity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_wall_amt
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1wall_1amt
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_lcliff_amt
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1lcliff_1amt
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_lfcliff_amt
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1lfcliff_1amt
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_rfcliff_amt
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1rfcliff_1amt
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_rcliff_amt
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1rcliff_1amt
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_bay_DI
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1bay_1DI
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_bay_AI
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1bay_1AI
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_song_number
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1song_1number
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_song_playing
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1song_1playing
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_number_of_stream_packets
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1number_1of_1stream_1packets
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_requested_velocity
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1requested_1velocity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_requested_radius
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1requested_1radius
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_requested_right_velocity
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1requested_1right_1velocity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    get_create_requested_left_velocity
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_get_1create_1requested_1left_1velocity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cbc_low_Create
 * Method:    create_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1stop
  (JNIEnv *, jobject);

/*
 * Class:     cbc_low_Create
 * Method:    create_drive
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1drive
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_drive_straight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1drive_1straight
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_spin_CW
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1spin_1CW
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_spin_CCW
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1spin_1CCW
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_drive_direct
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1drive_1direct
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_spin_block
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_create_1spin_1block
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_advance_led
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1advance_1led
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_play_led
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1play_1led
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_power_led
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1power_1led
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_digital_output
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1digital_1output
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_pwm_low_side_drivers
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1pwm_1low_1side_1drivers
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_low_side_drivers
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1low_1side_1drivers
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_load_song
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1load_1song
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_play_song
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1play_1song
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_read_block
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_cbc_low_Create_create_1read_1block
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     cbc_low_Create
 * Method:    create_write_byte
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1write_1byte
  (JNIEnv *, jobject, jchar);

/*
 * Class:     cbc_low_Create
 * Method:    create_clear_serial_buffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_low_Create_create_1clear_1serial_1buffer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
