/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cbc_low_Device */

#ifndef _Included_cbc_low_Device
#define _Included_cbc_low_Device
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbc_low_Device
 * Method:    power_level
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_cbc_low_Device_power_1level
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
