#!/bin/sh
COMPILER=./compiler
LINKER=./linker

CBC_DEVICE=./cbc_low_Device
CBC_DISPLAY=./cbc_low_Display
CBC_INPUT=./cbc_low_Input
CBC_MOTOR=./cbc_low_Motor
CBC_SENSOR=./cbc_low_Sensor
CBC_SERVO=./cbc_low_Servo
CBC_SOUND=./cbc_low_Sound
CBC_CAMERA=./cbc_low_Camera
CBC_CREATE=./cbc_low_Create

echo "Compiling CBC_Device..."
$COMPILER ${CBC_DEVICE}.c
echo "Compiling CBC_Display..."
$COMPILER ${CBC_DISPLAY}.c
echo "Compiling CBC_Input..."
$COMPILER ${CBC_INPUT}.c
echo "Compiling CBC_Motor..."
$COMPILER ${CBC_MOTOR}.c
echo "Compiling CBC_Sensor..."
$COMPILER ${CBC_SENSOR}.c
echo "Compiling CBC_Servo..."
$COMPILER ${CBC_SERVO}.c
echo "Compiling CBC_Sound..."
$COMPILER ${CBC_SOUND}.c
echo "Compiling CBC_Camera..."
$COMPILER ${CBC_CAMERA}.c
echo "Compiling CBC_Create..."
$COMPILER ${CBC_CREATE}.c
echo "Linking wrapper..."
$LINKER ${CBC_DEVICE}.o ${CBC_DISPLAY}.o ${CBC_INPUT}.o ${CBC_MOTOR}.o ${CBC_SENSOR}.o ${CBC_SERVO}.o ${CBC_SOUND}.o ${CBC_CAMERA}.o ${CBC_CREATE}.o
echo "Generated CBC.so!"

